env:
  es2021: true
  browser: true
  node: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended

ignorePatterns:
  - '**/public/**/*.js'

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  arrow-parens:
    - error
    - always
  curly:
    - error
    - all
  no-else-return:
    - error
    - allowElseIf: false
  no-duplicate-imports:
    - error
    - includeExports: true
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowTypedFunctionExpressions: true
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  import/no-unresolved:
    - off
  import/no-named-as-default-member:
    - off
  import/no-default-export:
    - error
  jsx-quotes:
    - error
    - prefer-double