extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss

plugins:
  - stylelint-scss

rules:
  max-nesting-depth: 1
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global